INFO:infra.sqlalchemy.dao.listen_to_db_notifications:Conectado ao PostgreSQL para escutar notificações.
INFO:infra.sqlalchemy.dao.listen_to_db_notifications:Listener registrado para o canal 'row_changed'.
parts  ['CCI BB ', ' 30.06.2024 ', ' Relatório sobre o sistema de controles internos BB ', ' Res. 4.910 e BCB 130']
parts  ['CCI BB BI ', ' 30.06.2024 ', ' Relatório sobre o sistema de controles internos ', ' Res. 4.910 e BCB 130']
parts  ['CCI BB Consórcios ', ' 30.06.2024 ', ' Relatório sobre sistema controle interno BACEN ', ' Res. 4.910 e BCB 260']
parts  ['CCI BB Leasing ', ' 30.06.2024 ', ' BCB 130 062024']
parts  ['CCI BB ', ' 30/06/2024']
parts  ['CCI BB ', ' 30/06/2024']
parts  ['CCI BB ', ' 30/06/2024']
parts  ['CCI BB BI ', ' 30/06/2024']
parts  ['CCI BB BI ', ' 30/06/2024']
parts  ['CCI BB Consórcios ', ' 30/06/2024']
parts  ['CCI BB Consórcios ', ' 30/06/2024']
parts  ['CCI BB Leasing ', ' 30/06/2024']
INFO:     192.168.203.129:37364 - "POST /apiptai/upload-rcm-excel-multiplos HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/routers/rotas_upload.py", line 336, in upload_rcm_excel_multiplos
    novo_id = await inserir_linha_rcm(
TypeError: inserir_linha_rcm() got an unexpected keyword argument 'ano'
